// ============================================================
// MONDAY — What Is Reality? / Authority We Choose
// ============================================================

module.exports = {
  label: 'Monday',
  key: 'mon',

  // ──────────────────────────────────────────────
  // LIFE'S FUNDAMENTAL: What Is Reality?
  // ──────────────────────────────────────────────
  fundamental: {
    title: 'What Is Reality?',
    question: 'Am I growing in God\'s reality?',
    description:
      'God and His character - Our reality comes from the Author who created and defined the nature, design, ' +
      'context, morality, and purpose of everything that exists. We know there is an Author because nothing ' +
      'comes from nothing, and nothing in the universe is the source of itself. Moreover, our reality extends ' +
      'beyond the limits of human understanding; only the Author, Authority, and Creator of the universe ' +
      'understands it fully. Our reality expresses the character and aspirations of God--what is truly good ' +
      'and what constitutes the good life, the joy set before us. To discover our reality, the good life, ' +
      'such knowledge must be found in and through God, who reveals Himself through creation, His Word, His ' +
      'law, His rule, the Trinity, the Father, the Son, the Spirit, the Saints, and history.',

    passages: [
      {
        title: 'Creation',
        ref: 'Genesis 1',
        summary: 'Reality is designed by God.',
        rq: 'Do I live by man\'s view of reality or God\'s?',
        verses: 'Genesis 1',
      },
      {
        title: 'Tower of Babel',
        ref: 'Genesis 11:1-9',
        summary: 'Man attempts to control and define reality and value.',
        rq: 'Do I live believing by God\'s reality or man\'s?',
        verses: 'Genesis 11:1-9',
      },
      {
        title: 'Abram in Egypt',
        ref: 'Genesis 12:10–20',
        summary: 'Fear causes us to lose sight of the bigger picture.',
        rq: 'Do I live from fear or trusting in God?',
        verses: 'Genesis 12:10-20',
      },
      {
        title: 'Joseph Sold Into Slavery',
        ref: 'Genesis 37',
        summary: 'God is bigger than our circumstances.',
        rq: 'Do I interpret hardship through trust in God -- or despair?',
        verses: 'Genesis 37',
      },
      {
        title: 'Joseph Exalted by God',
        ref: 'Genesis 41',
        summary: 'God is the source of truth, reality and good.',
        rq: 'Do I pursue God for understanding and good?',
        verses: 'Genesis 41',
      },
      {
        title: 'Israel\'s Oppression',
        ref: 'Exodus 1',
        summary: 'Man can appear in control, but God alone defines reality.',
        rq: 'Do I interpret life through man -- or through God?',
        verses: 'Exodus 1',
      },
      {
        title: 'The Burning Bush',
        ref: 'Exodus 3',
        summary: 'Understanding reality begins with God\'s revelation.',
        rq: 'Do I posture my life so that I can recognize and listen to God?',
        verses: 'Exodus 3',
      },
      {
        title: 'The Plagues',
        ref: 'Exodus 11',
        summary: 'Pride keeps us from seeing false realities.',
        rq: 'Am I open to God challenging what I mistakenly trust?',
        verses: 'Exodus 11',
      },
      {
        title: 'Passover',
        ref: 'Exodus 12',
        summary: 'Deliverance comes from God.',
        rq: 'Do I pursue God to rescue me from myself?',
        verses: 'Exodus 12',
      },
      {
        title: 'Crossing the Red Sea',
        ref: 'Exodus 14',
        summary: 'What appears impossible, can be the stage for seeing reality.',
        rq: 'Do I trust God when the path seems impossible?',
        verses: 'Exodus 14',
      },
      {
        title: 'Manna from Heaven',
        ref: 'Exodus 16',
        summary: 'Daily dependence on God opens our eyes to reality.',
        rq: 'Do I increasingly desire to be dependent on God?',
        verses: 'Exodus 16',
      },
      {
        title: 'Water from the Rock',
        ref: 'Exodus 17:1-7',
        summary: 'God sustains life from sources we would never expect.',
        rq: 'Do I increasingly recognize and desire God\'s provision?',
        verses: 'Exodus 17:1-7',
      },
      {
        title: 'Recognizing God',
        ref: 'Deuteronomy 8',
        summary: 'God is the source of reality and good.',
        rq: 'Do I increasingly recognize what is good?',
        verses: 'Deuteronomy 8',
      },
      {
        title: 'Elijah on Mount Carmel',
        ref: '1 Kings 18',
        summary: 'Reality is found in God.',
        rq: 'Do I look to God even when I am alone?',
        verses: '1 Kings 18',
      },
      {
        title: 'Isaiah\'s Vision of the Throne',
        ref: 'Isaiah 6',
        summary: 'Reality, God, is far grander than we know.',
        rq: 'Does God\'s greatness shape how I live?',
        verses: 'Isaiah 6',
      },
      {
        title: 'The Virgin Birth',
        ref: 'Matthew 1:18–25',
        summary: 'Reality is defined by God.',
        rq: 'Do I look to God to define reality?',
        verses: 'Matthew 1:18-25',
      },
      {
        title: 'The Magi Seek the King',
        ref: 'Matthew 2:1–12',
        summary: 'Some pursue reality while others ignore it.',
        rq: 'Do I seek God and the reality found in Him?',
        verses: 'Matthew 2:1-12',
      },
      {
        title: 'The Gospel',
        ref: 'Matthew 5:1–12',
        summary: 'Blessing is found in the Kingdom of God.',
        rq: 'Do I pursue and live in the kingdom of God?',
        verses: 'Matthew 5:1-12',
      },
      {
        title: 'I Will Give You Rest',
        ref: 'Matthew 11:25–30',
        summary: 'Reality and rest is found in God, not man\'s power.',
        rq: 'Do I pursue a life of rest, yoked to God?',
        verses: 'Matthew 11:25-30',
      },
      {
        title: 'Mustard Seed & Yeast',
        ref: 'Matthew 13:31–35',
        summary: 'What appears insignificant to most turns out to be very significant.',
        rq: 'Do I trust God\'s transforming wisdom and power?',
        verses: 'Matthew 13:31-35',
      },
      {
        title: 'The Authority of Jesus Astonishes',
        ref: 'Mark 1:21–28',
        summary: 'Authority is seen in revealed reality.',
        rq: 'Do I recognize God\'s authority?',
        verses: 'Mark 1:21-28',
      },
      {
        title: 'Jesus Heals the Paralytic',
        ref: 'Mark 2:1–12',
        summary: 'Authority is seen in the restoring what is broken.',
        rq: 'Do I place my broken life into God\'s restoring hands?',
        verses: 'Mark 2:1-12',
      },
      {
        title: 'The Gerasene Demoniac Restored',
        ref: 'Mark 5:1–20',
        summary: 'God has the authority to redeem.',
        rq: 'Do I believe God can restore what seems impossible?',
        verses: 'Mark 5:1-20',
      },
      {
        title: 'Jesus Walks on Water',
        ref: 'Mark 6:45–52',
        summary: 'Reality exceeds man\'s understanding.',
        rq: 'Do I look to God to define the reality I live by?',
        verses: 'Mark 6:45-52',
      },
      {
        title: 'The Transfiguration',
        ref: 'Mark 9:2–8',
        summary: 'The eternal glory of the redeemed is hidden.',
        rq: 'Does my potential for eternal glory shape how I live?',
        verses: 'Mark 9:2-8',
      },
      {
        title: 'The Resurrection',
        ref: 'Mark 16:1–8',
        summary: 'Death is not ultimate reality -- God is.',
        rq: 'Do I live from an eternal perspective?',
        verses: 'Mark 16:1-8',
      },
      {
        title: 'Gabriel Announces Jesus\' Birth',
        ref: 'Luke 1:26–56',
        summary: 'Reality is increasingly seen as we increasingly believe God.',
        rq: 'Am I increasingly believing in God\'s view of reality?',
        verses: 'Luke 1:26-56',
      },
      {
        title: 'The Birth of Jesus',
        ref: 'Luke 2:1–20',
        summary: 'Our example, Jesus, entering humbly under God.',
        rq: 'Do I see the greatness of humility?',
        verses: 'Luke 2:1-20',
      },
      {
        title: 'Jesus in the Temple at Twelve',
        ref: 'Luke 2:41–52',
        summary: 'Jesus pursues reality.',
        rq: 'Does God\'s reality and purposes organize my life?',
        verses: 'Luke 2:41-52',
      },
      {
        title: 'The Great Catch of Fish',
        ref: 'Luke 5:1–11',
        summary: 'In humility, reality becomes increasingly visible.',
        rq: 'Do I grasp the fundamental value of humility?',
        verses: 'Luke 5:1-11',
      },
      {
        title: 'Calming the Storm',
        ref: 'Luke 8:22–25',
        summary: 'Reality is not the storm but God.',
        rq: 'Does fear or faith interpret my circumstances?',
        verses: 'Luke 8:22-25',
      },
      {
        title: 'The Word Became Flesh',
        ref: 'John 1:1–14',
        summary: 'Reality is not abstract, it is personal and recognizable.',
        rq: 'Am I open to seeing reality through Jesus?',
        verses: 'John 1:1-14',
      },
      {
        title: 'The Lamb of God',
        ref: 'John 1:29–34',
        summary: 'Redemption centers on humility, believing and desiring God.',
        rq: 'Do I live aware of my need for God\'s grace?',
        verses: 'John 1:29-34',
      },
      {
        title: 'You Must Be Born Again',
        ref: 'John 3:1–21',
        summary: 'Reality is found through God\'s grace.',
        rq: 'Do I live being led by the Spirit?',
        verses: 'John 3:1-21',
      },
      {
        title: 'Living Water',
        ref: 'John 4:1–26',
        summary: 'God satisfies the deepest thirst of the soul.',
        rq: 'Do I seek fulfillment in God?',
        verses: 'John 4:1-26',
      },
      {
        title: 'Bread of Life',
        ref: 'John 6:25–40',
        summary: 'Reality is sustained by God.',
        rq: 'Do I hunger for God?',
        verses: 'John 6:25-40',
      },
      {
        title: 'Raising Lazarus',
        ref: 'John 11:1-46',
        summary: 'Reality is not defined by physical death but by God.',
        rq: 'Does God define my values and beliefs?',
        verses: 'John 11:1-46',
      },
      {
        title: 'Ananias and Sapphira',
        ref: 'Acts 5:1-11',
        summary: 'Reality is not manipulated by appearances or performances.',
        rq: 'Do I live transparently believing and desiring God?',
        verses: 'Acts 5:1-11',
      },
      {
        title: 'Saul\'s Conversion',
        ref: 'Acts 9:1-19',
        summary: 'Reality can overturn deeply held convictions.',
        rq: 'Am I open to God defining the reality that governs my life?',
        verses: 'Acts 9:1-19',
      },
      {
        title: 'Paul in Athens',
        ref: 'Acts 17:16-34',
        summary: 'Reality confronts cultural philosophies.',
        rq: 'Do I interpret reality through God\'s revelation or culture?',
        verses: 'Acts 17:16-34',
      },
      {
        title: 'Man\'s Digression from Reality',
        ref: 'Romans 1:18-32',
        summary: 'Pride does not want to be governed by Reality.',
        rq: 'Do I live humbly before God?',
        verses: 'Romans 1:18-32',
      },
      {
        title: 'Seeing Reality',
        ref: 'Romans 8:1-17',
        summary: 'Reality seen living according to the Spirit.',
        rq: 'Is my life being led by the Spirit?',
        verses: 'Romans 8:1-17',
      },
      {
        title: 'The Supremacy of Christ',
        ref: 'Colossians 1:13-29',
        summary: 'God holds Reality in His hand.',
        rq: 'Is God central to the reality I live by?',
        verses: 'Colossians 1:13-29',
      },
    ],
  },

  // ──────────────────────────────────────────────
  // RESPONDING WELL: Authority We Choose
  // ──────────────────────────────────────────────
  response: {
    title: 'Authority',
    question: 'Do I increasingly live by God\'s authority?',
    description:
      'the Great Commission:   All authority has been given to me\n' +
      'the Lord\'s Prayer:        Our Father in heaven\n\n' +
      'All our issues in life are answered by God\n\n' +
      'Everyone chooses an authority shaping their values, beliefs and desires of reality, morality, and ' +
      'purpose determining who they are becoming and how they live. While people often place authority in ' +
      'themselves, others, or culture, true life and good come only from following God as the ultimate ' +
      'authority--the One who fully understands our nature, life and eternity. Pride leads us to wrongly ' +
      'assume control we are not equipped for, resulting in deception and brokenness, whereas humility opens ' +
      'the way to God\'s wisdom, stability, and truth. Through a growing relationship with God as our Father ' +
      'and the example of Jesus we learn to live in alignment with reality, increasingly responding with ' +
      'God\'s character of love rather than fear or self-reliance. In doing so, we discover that all of ' +
      'life\'s deepest questions and struggles are answered in God, and that true joy, purpose, and the ' +
      '"good life" are found in living under His authority.',

    passages: [
      {
        title: 'The Fall',
        ref: 'Genesis 3',
        summary: 'We reject God, pursuing the illusion of man\'s autonomy.',
        rq: 'Who does my life and values identify is my authority?',
        verses: 'Genesis 3',
      },
      {
        title: 'Cain and Abel',
        ref: 'Genesis 4:1-15',
        summary: 'God warns us: "sin is crouching at your door..."',
        rq: 'Do I heed God\'s warning?',
        verses: 'Genesis 4:1-15',
      },
      {
        title: 'Noah',
        ref: 'Genesis 6',
        summary: 'God sees what we don\'t see.',
        rq: 'Do I believe in God when I can\'t see the good?',
        verses: 'Genesis 6',
      },
      {
        title: 'Call of Abram',
        ref: 'Genesis 12',
        summary: 'God\'s call is much bigger than we can see.',
        rq: 'Do I hear and respond to God\'s promptings?',
        verses: 'Genesis 12',
      },
      {
        title: 'Abraham Offering Isaac',
        ref: 'Genesis 22',
        summary: 'Authority and character is identified trusting in God.',
        rq: 'Is my trust in God increasingly growing?',
        verses: 'Genesis 22',
      },
      {
        title: 'Sodom and Gomorrah',
        ref: 'Genesis 19:1-29',
        summary: 'Society increasingly normalizes rebellion.',
        rq: 'Does the culture shape my convictions?',
        verses: 'Genesis 19:1-29',
      },
      {
        title: 'Joseph and Potiphar\'s Wife',
        ref: 'Genesis 39',
        summary: 'Our beliefs are identified in our morality.',
        rq: 'Does the morality God has given us guide my life?',
        verses: 'Genesis 39',
      },
      {
        title: 'Moses\' Reluctance',
        ref: 'Exodus 4',
        summary: 'We desire to do what we believe in.',
        rq: 'Do I believe in God when He calls?',
        verses: 'Exodus 4',
      },
      {
        title: 'Pharaoh Hardens His Heart',
        ref: 'Exodus 11',
        summary: 'Resisting God does not preserve freedom -- it deepens bondage.',
        rq: 'Is my heart open and responsive to God?',
        verses: 'Exodus 11',
      },
      {
        title: 'The Ten Commandments',
        ref: 'Exodus 20',
        summary: 'God is not about restrictions but the architecture of freedom.',
        rq: 'Do I view God\'s commands as life-giving?',
        verses: 'Exodus 20',
      },
      {
        title: 'The Golden Calf',
        ref: 'Exodus 32',
        summary: 'When we are distant from God, we manufacture substitutes for God.',
        rq: 'Do my values point to God or substitutes?',
        verses: 'Exodus 32',
      },
      {
        title: 'The Law',
        ref: 'Deuteronomy 5',
        summary: 'God orders life so that it flourishes.',
        rq: 'Does my life reflect believing in and desiring God\'s authority?',
        verses: 'Deuteronomy 5',
      },
      {
        title: 'Joshua\'s Farewell',
        ref: 'Joshua 23',
        summary: 'Personal life requires a conscious choosing.',
        rq: 'What does my life\'s values indicate I am choosing?',
        verses: 'Joshua 23',
      },
      {
        title: 'Saul Rejected',
        ref: '1 Samuel 13:1-14',
        summary: 'Our values and beliefs direct our destiny.',
        rq: 'Is my life a reflection of believing and desiring God?',
        verses: '1 Samuel 13:1-14',
      },
      {
        title: 'Josiah Rediscovers the Law',
        ref: '2 Kings 22–23',
        summary: 'God identifies reality.',
        rq: 'Does the Bible govern my beliefs and desires?',
        verses: '2 Kings 22-23',
      },
      {
        title: 'Daniel under God',
        ref: 'Daniel 1',
        summary: 'God\'s authority defines reality, not kings.',
        rq: 'Do I remain faithful to God, even when facing pressure?',
        verses: 'Daniel 1',
      },
      {
        title: 'Personal Relationships',
        ref: 'Matthew 5:21-48',
        summary: 'Jesus identifies character yielding good personal relationships.',
        rq: 'Does my life increasingly reflect such character?',
        verses: 'Matthew 5:21-48',
      },
      {
        title: 'Kingdom Living',
        ref: 'Matthew 6:1-34',
        summary: 'What we increasingly seek reveals what we value.',
        rq: 'Does God\'s values organize my life and my priorities?',
        verses: 'Matthew 6:1-34',
      },
      {
        title: 'Kingdom Living',
        ref: 'Matthew 7:1-29',
        summary: 'God defines life\'s true values.',
        rq: 'Does God\'s values organize my life and my priorities?',
        verses: 'Matthew 7:1-29',
      },
      {
        title: 'Forgiving the Paralytic',
        ref: 'Matthew 9:1-8',
        summary: 'Jesus has authority over life and sin.',
        rq: 'Do I value God\'s authority over man\'s power?',
        verses: 'Matthew 9:1-8',
      },
      {
        title: 'Jesus Sends Out the Twelve',
        ref: 'Matthew 10',
        summary: 'God\'s Authority is experienced living in God\'s kingdom.',
        rq: 'Do I live in and desire God\'s kingdom?',
        verses: 'Matthew 10',
      },
      {
        title: 'Workers in the Vineyard',
        ref: 'Matthew 20:1-16',
        summary: 'God\'s authority is not about human comparison but love.',
        rq: 'Do I trust God\'s wisdom when it challenges my expectations?',
        verses: 'Matthew 20:1-16',
      },
      {
        title: 'Parable of the Landlord',
        ref: 'Matthew 21:33-46',
        summary: 'Rejecting God\'s authority is rejecting the life He offers.',
        rq: 'Does my life honor and live by God\'s authority?',
        verses: 'Matthew 21:33-46',
      },
      {
        title: 'Woe to the Pharisees',
        ref: 'Matthew 23',
        summary: 'Performances can deceive what we truly believe and desire.',
        rq: 'What does my life reflect are my values, what I believe and desire?',
        verses: 'Matthew 23',
      },
      {
        title: 'Sheep and Goats Judgment',
        ref: 'Matthew 25:31-46',
        summary: 'Our life reveals who we choose to be our authority.',
        rq: 'Does my life reflect the values of Jesus?',
        verses: 'Matthew 25:31-46',
      },
      {
        title: 'A House Divided Cannot Stand',
        ref: 'Mark 3:20-30',
        summary: 'Rejecting God\'s authority diverts life away from reality.',
        rq: 'Do my values align with God\'s?',
        verses: 'Mark 3:20-30',
      },
      {
        title: 'Withered Hand Restored',
        ref: 'Mark 3:1-6',
        summary: 'God prioritizes love over legalism.',
        rq: 'Does God\'s character of love increasingly govern my life?',
        verses: 'Mark 3:1-6',
      },
      {
        title: 'Take Up Your Cross',
        ref: 'Mark 8:31-38',
        summary: 'God identifies the two opposing paths in life.',
        rq: 'Do my values reflect following God or man\'s power?',
        verses: 'Mark 8:31-38',
      },
      {
        title: 'The Rich Young Ruler',
        ref: 'Mark 10:17-31',
        summary: 'Our values expose what we believe and desire.',
        rq: 'Do my values reflect God is my priority?',
        verses: 'Mark 10:17-31',
      },
      {
        title: 'The Great Commandment',
        ref: 'Mark 12:28-34',
        summary: 'God orders life in God\'s character of love.',
        rq: 'Does God\'s character of love reflect my priorities?',
        verses: 'Mark 12:28-34',
      },
      {
        title: 'Jesus\' Temptation',
        ref: 'Luke 4:1-13',
        summary: 'God and His Word is our authority.',
        rq: 'Is God and His character increasingly governing my life?',
        verses: 'Luke 4:1-13',
      },
      {
        title: 'Jesus Declares His Mission',
        ref: 'Luke 4:16-21',
        summary: 'Jesus aligns His life with His Father.',
        rq: 'Do I align myself with God\'s purposes?',
        verses: 'Luke 4:16-21',
      },
      {
        title: 'The Centurion\'s Faith',
        ref: 'Luke 7:1-10',
        summary: 'Authority is recognized through alignment with reality.',
        rq: 'Do I trust God is the authority of reality?',
        verses: 'Luke 7:1-10',
      },
      {
        title: 'Jesus Before Pilate',
        ref: 'Luke 23:1-25',
        summary: 'True authority remains unthreatened by man\'s power.',
        rq: 'Do I stand secure in God independent of circumstance?',
        verses: 'Luke 23:1-25',
      },
      {
        title: 'Calling the First Disciples',
        ref: 'John 1:35–51',
        summary: 'Disciples believe in and desire their Authority.',
        rq: 'Do I believe in and desire God and His character?',
        verses: 'John 1:35-51',
      },
      {
        title: 'The Good Shepherd',
        ref: 'John 10:1-18',
        summary: 'Authority leads for good.',
        rq: 'Do I recognize and trust the Shepherd\'s voice?',
        verses: 'John 10:1-18',
      },
      {
        title: 'Peter and John Before the Sanhedrin',
        ref: 'Acts 4',
        summary: 'God\'s authority far outweighs man\'s authority.',
        rq: 'Do I increasingly believe in and desire God\'s authority?',
        verses: 'Acts 4',
      },
      {
        title: 'Paul Before the Council',
        ref: 'Acts 23:1-11',
        summary: 'What we believe and desire is reflected by our life.',
        rq: 'Is God reflected by my values, my living?',
        verses: 'Acts 23:1-11',
      },
    ],
  },
};
